# Auto-generated by mtbmcp. Do not edit manually.
import json as _json

SESSION_INFO = _json.loads(r'''{
  "extension_dir": "c:/Users/Mashiro/.vscode/extensions/infineonag.modustoolbox-ai-0.5.0-win32-x64",
  "workspace_path": "d:/CodeProjects/MCUProjects/cy8c4149-s595-34ch-cs5-curvatouch",
  "projects": [
    "cy8c4149-s595-34ch-cs5-curvatouch"
  ],
  "device_name": "CY8C4149AZQ-S595",
  "bsp_name": "",
  "board_target": "",
  "cy_tools_path": "D:/Development/Infineon/ModusToolbox/tools_3.9",
  "modus_shell_path": "D:/Development/Infineon/ModusToolbox/tools_3.9/modus-shell",
  "tcp_port": 61575,
  "ext_port": 54707,
  "pid": 5028,
  "log_level": "info",
  "log_file": "C:/Users/Mashiro/AppData/Local/Temp/mtbai-logs/mtbai.log"
}''')

for _key, _value in SESSION_INFO.items():
    globals()[_key.upper()] = _value

del _json
del _key
del _value
